version: '3.7'

services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:${TAG:-latest}
    build:
      context: ./backend
    env_file:
      - .env.dev

  db:
    image: postgres:12.3-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env.dev

  redis:
    image: redis:6.0-alpine
    volumes:
      - redisdata:/data

volumes:
  static:
  redisdata:
  postgresdata:
